/* eslint-disable test/no-import-node-test */
import assert from 'node:assert/strict'
import { existsSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const root = new URL('../', import.meta.url)

async function read(path) {
  return readFile(new URL(path, root), 'utf8')
}

test('desktop GPT-Live stays a global header control before pairing', async () => {
  const header = await read('src/frontend/components/popup/PopupHeader.vue')
  const liveButton = header.indexOf('data-codex-live-phase')
  const pairingButton = header.indexOf('title="显示手机连接二维码"')

  assert.ok(liveButton >= 0, 'missing desktop GPT-Live header control')
  assert.ok(pairingButton >= 0, 'missing existing pairing control')
  assert.ok(liveButton < pairingButton, 'GPT-Live must remain immediately before the pairing controls')
  assert.match(header, /prefers-reduced-motion: reduce/)
  assert.match(header, /aria-pressed="codexLiveActive"/)
  assert.match(header, /CODEX_LIVE_LONG_PRESS_MS = 5_000/)
  assert.match(header, /emit\('toggleCodexLiveMute'\)/)
})

test('desktop GPT-Live uses WebRTC and a one-shot desktop bridge capability', async () => {
  const manager = await read('src/frontend/composables/useDesktopCodexLive.ts')
  const broker = await read('src/rust/bridge/codex_live.rs')

  assert.match(manager, /navigator\.mediaDevices\.getUserMedia/)
  assert.match(manager, /new RTCPeerConnection\(\)/)
  assert.match(manager, /get_bridge_desktop_token/)
  assert.match(manager, /path: '\/ws\/codex-live'/)
  assert.match(manager, /iterate\.desktop-token\.\$\{token\}/)
  assert.match(manager, /set_codex_live_audio_reserved/)
  assert.match(manager, /MAX_RECONNECT_ATTEMPTS = 3/)
  assert.match(manager, /traceLiveDiagnostics\('broker_error'/)
  assert.match(manager, /traceLiveDiagnostics\('broker_socket_error'/)
  assert.match(manager, /traceLiveDiagnostics\('broker_socket_close'/)
  assert.match(broker, /thread_resume_requires_replacement/)
  assert.match(broker, /already has an active writer/)
  assert.match(broker, /\[codex-live\] start failed/)
})

test('desktop Live reserves the microphone without changing the Fn shortcut setting', async () => {
  const nativeSpeech = await read('src/rust/native_speech/mod.rs')
  const phase1 = await read('src/rust/native_speech/phase1.rs')
  const appContent = await read('src/frontend/components/AppContent.vue')

  assert.match(nativeSpeech, /CODEX_LIVE_AUDIO_RESERVED/)
  assert.match(nativeSpeech, /set_codex_live_audio_reserved\(app: AppHandle, reserved: bool\)/)
  assert.match(nativeSpeech, /if reserved \{[\s\S]*if let Err\(error\) = reveal_overlay\(&app\)[\s\S]*else \{[\s\S]*if let Err\(error\) = hide_overlay\(&app\)/)
  assert.match(phase1, /SpeechEffect::HideOverlay[\s\S]*codex_live_audio_reserved\(\)[\s\S]*reveal_overlay/)
  assert.match(nativeSpeech, /fn-toggle-suppressed-codex-live/)
  assert.match(appContent, /handleToggleCodexLive/)
  assert.doesNotMatch(appContent, /handleToggleCodexLive[\s\S]{0,900}set_global_shortcut_enabled/)
})

test('a bare Control tap toggles mute only while GPT-Live owns the microphone', async () => {
  const fnListener = await read('src/rust/native_speech/fn_listener.rs')
  const speechRuntime = await read('src/rust/native_speech/phase1.rs')

  assert.match(speechRuntime, /FnListenerEvent::ControlTapped[\s\S]{0,220}codex_live_audio_reserved\(\)[\s\S]{0,160}dispatch_desktop_codex_live_fn_action\("mute"\)/)
  assert.match(fnListener, /CONTROL_TAP_MAX_US: u64 = 800_000/)
  assert.match(fnListener, /KEY_CODE_CONTROL_LEFT: u16 = 59/)
  assert.match(fnListener, /KEY_CODE_CONTROL_RIGHT: u16 = 62/)
  assert.match(fnListener, /CGEventTapOptions::ListenOnly/)
  assert.match(fnListener, /CGEventType::KeyDown/)
  assert.match(fnListener, /CGEventType::ScrollWheel/)
  assert.match(fnListener, /FnListenerEvent::ControlTapped/)
})

test('a short Fn press stops every live GPT-Live phase and falls back to ordinary dictation while idle', async () => {
  const bridge = await read('src/rust/bridge/ws.rs')
  const speechRuntime = await read('src/rust/native_speech/phase1.rs')

  assert.match(speechRuntime, /FnReleaseAction::Short[\s\S]{0,120}dispatch_desktop_codex_live_fn_action\("short"\)/)
  assert.match(bridge, /requested_action == "short"[\s\S]{0,240}"preparing" \| "connecting" \| "active" \| "reconnecting"[\s\S]{0,120}"stop"\.to_string\(\)/)
  assert.match(bridge, /desktop_codex_live_short_press_stops_every_live_phase_and_idle_falls_back/)
  assert.match(bridge, /desktop_codex_live_short_press_replaces_a_pending_start_with_stop/)
  assert.match(speechRuntime, /StatusCode::NO_CONTENT && action == "short"[\s\S]{0,80}return Ok\(false\)/)
  assert.match(speechRuntime, /Ok\(false\) => \{[\s\S]{0,100}send_control_input\(SpeechControlInput::FnPressed\)/)
})

test('the disposable popup controls the canonical speech overlay host through the authenticated bridge', async () => {
  const appContent = await read('src/frontend/components/AppContent.vue')
  const desktopLive = await read('src/frontend/composables/useDesktopCodexLive.ts')
  const host = await read('src/frontend/composables/useDesktopCodexLiveHost.ts')
  const control = await read('src/frontend/services/desktopCodexLiveControl.ts')
  const bridge = await read('src/rust/bridge/ws.rs')
  const publicControl = await read('src/rust/bridge/public_control.rs')
  const sharedPill = await read('src/frontend/components/speech/SpeechWavePill.vue')
  const speechOverlay = await read('src/frontend/components/speech/InfinitySpeechAnchor.vue')
  const hudLayout = await read('src/frontend/composables/useDesktopCodexLiveHudLayout.ts')
  const hudAnimation = await read('src/rust/native_speech/hud_animation.rs')
  const mainLayout = await read('src/frontend/components/layout/MainLayout.vue')
  const tauriConfig = await read('tauri.conf.json')
  const fnListener = await read('src/rust/native_speech/fn_listener.rs')
  const speechRuntime = await read('src/rust/native_speech/phase1.rs')

  assert.match(sharedPill, /speech-wave-pill/)
  assert.match(speechOverlay, /SpeechWavePill/)
  assert.match(speechOverlay, /useDesktopCodexLiveHost/)
  assert.match(speechOverlay, /liveHost\.initialize\(\)/)
  assert.match(speechOverlay, /liveHost\.dispose\(\)/)
  assert.match(speechOverlay, /const live = liveHost\.live/)
  assert.match(speechOverlay, /liveHost\.requestMicrophoneMuteToggle\(\)/)
  assert.doesNotMatch(speechOverlay, /getDesktopCodexLiveSnapshot|LIVE_POLL_INTERVAL_MS/)
  assert.doesNotMatch(speechOverlay, /DESKTOP_CODEX_LIVE_UI_SNAPSHOT_EVENT|listen<DesktopCodexLiveUiSnapshot>/)
  assert.match(speechOverlay, /resolveCodexLiveHudText/)
  assert.match(speechOverlay, /executionPhase\.value === 'running'/)
  assert.match(speechOverlay, /useDesktopCodexLiveHudLayout\(SPEECH_OVERLAY_POSITION_KEY\)/)
  assert.match(speechOverlay, /live-overlay--expanded/)
  assert.match(speechOverlay, /live-overlay--collapsed/)
  assert.match(speechOverlay, /-webkit-line-clamp: 6/)
  assert.match(speechOverlay, /live-overlay__mute/)
  assert.match(speechOverlay, /live-overlay__fold/)
  assert.match(speechOverlay, /const brandLabel = 'iterate'/)
  assert.match(speechOverlay, /const manuallyCollapsed = ref\(false\)/)
  assert.match(speechOverlay, /const layoutMode = computed/)
  assert.match(speechOverlay, /handleFoldPointerEnd\(\$event, true\)/)
  assert.match(speechOverlay, /handleFoldPointerEnd\(\$event, false\)/)
  assert.match(speechOverlay, /liveActive/)
  assert.match(speechOverlay, /await Promise\.all\(\[/)
  assert.match(speechOverlay, /overlayWindow\.startDragging/)
  assert.match(speechOverlay, /aria-live="polite"[\s\S]{0,80}data-tauri-drag-region/)
  const expandedHudStyle = speechOverlay.match(/\.live-overlay--expanded\s*\{([^}]*)\}/)?.[1] ?? ''
  assert.match(expandedHudStyle, /background:\s*transparent/)
  assert.match(expandedHudStyle, /cursor:\s*grab/)
  assert.doesNotMatch(expandedHudStyle, /border(?:-radius)?:|box-shadow:|backdrop-filter:/)
  const panelHudStyle = speechOverlay.match(/\.live-overlay__panel\s*\{([^}]*)\}/)?.[1] ?? ''
  assert.match(panelHudStyle, /background:\s*linear-gradient/)
  assert.match(panelHudStyle, /border-radius:\s*13px/)
  assert.match(panelHudStyle, /backdrop-filter:\s*blur\(14px\)/)
  assert.match(panelHudStyle, /grid-template-columns:\s*minmax\(0, 1fr\) 34px 22px/)
  assert.doesNotMatch(speechOverlay, /\.live-overlay__(?:eyebrow|status)[\s\S]{0,500}text-shadow:/)
  const applySnapshotBody = speechOverlay.match(/function applyLiveUiSnapshot\([^)]*\)\s*\{([^}]*)\}/)?.[1] ?? ''
  assert.doesNotMatch(applySnapshotBody, /syncExpandedLayout/)
  assert.match(speechOverlay, /watch\(layoutMode, value => syncHudLayout\(value\)\)/)
  assert.match(hudLayout, /DesktopCodexLiveHudLayoutMode = 'compact' \| 'collapsed' \| 'expanded'/)
  assert.match(hudLayout, /let lastRequestedMode: DesktopCodexLiveHudLayoutMode \| null = null/)
  assert.match(hudLayout, /if \(lastRequestedMode === mode\)[\s\S]{0,100}return Promise\.resolve\(\)/)
  assert.match(hudLayout, /lastRequestedMode = mode[\s\S]{0,100}layoutQueue\.request\(mode\)/)
  assert.match(hudLayout, /DESKTOP_CODEX_LIVE_COLLAPSED_SIZE/)
  assert.match(hudLayout, /animate_speech_overlay_frame/)
  assert.match(hudLayout, /targetContentWidthPoints/)
  assert.match(hudLayout, /nativeFrameAnimationAvailable/)
  assert.match(hudLayout, /prefers-reduced-motion: reduce/)
  assert.match(hudLayout, /NATIVE_FRAME_SETTLE_MS = 180/)
  assert.match(hudLayout, /scheduleNativeCenterPersistence\(\)/)
  assert.match(hudLayout, /positionForRightEdgeCenter/)
  assert.match(hudLayout, /requestedCenter\.x \+ currentPhysicalWidth \/ 2/)
  assert.match(hudLayout, /Promise\.all\(\[\s*hudWindow\.scaleFactor\(\),\s*hudWindow\.outerPosition\(\),/)
  assert.match(hudLayout, /native frame animation unavailable; using Tauri fallback/)
  assert.match(hudAnimation, /NSAnimationContext/)
  assert.match(hudAnimation, /frameRectForContentRect_/)
  assert.match(hudAnimation, /NSScreen::visibleFrame/)
  assert.match(hudAnimation, /HUD_EDGE_MARGIN_PHYSICAL_PX \/ scale_factor/)
  assert.match(hudAnimation, /right_anchored_clamped_frame/)
  assert.match(hudAnimation, /current\.x \+ current\.width - target_width/)
  assert.doesNotMatch(hudAnimation, /PhysicalPosition|target_content_x|target_content_y/)
  assert.doesNotMatch(host, /getDesktopCodexLiveSnapshot\(\)/)
  assert.match(host, /reportDesktopCodexLiveStatus/)
  assert.match(host, /HOST_POLL_INTERVAL_MS = 250/)
  assert.match(host, /HEARTBEAT_INTERVAL_MS = 1500/)
  assert.match(host, /renewDesktopCodexLiveLease/)
  assert.match(host, /getCurrentWindow\(\)/)
  assert.doesNotMatch(host, /\.show\(\)/)
  assert.match(host, /await hostWindow\.hide\(\)/)
  assert.match(host, /canonical speech overlay remains hidden while idle/)
  assert.match(host, /LAST_PROJECT_STORAGE_KEY/)
  assert.match(host, /toggleDesktopCodexLive\(projectPath\)/)
  assert.match(host, /setDesktopCodexLiveMicrophoneMuted\(nextMuted\)/)
  assert.match(host, /live\.interruptCurrentConversation\(\)/)
  assert.match(host, /lifecycleRequestInFlight/)
  assert.match(host, /muteRequestInFlight/)
  assert.match(host, /live\.setMicrophoneMuted\(nextMuted\)[\s\S]{0,260}runCommand\(snapshot\)/)
  assert.match(host, /setMicrophoneMuted\(command\.microphone_muted/)
  assert.match(host, /desktop-codex-live-fn-action/)
  assert.doesNotMatch(host, /emit\(DESKTOP_CODEX_LIVE_UI_SNAPSHOT_EVENT/)
  assert.doesNotMatch(host, /get_speech_runtime_status/)
  assert.match(host, /operation = \(async \(\) =>/)
  assert.match(host, /commandGuard\.issue\(serverEpoch, snapshot\.revision\)/)
  assert.match(host, /const requestEpoch = serverEpoch/)
  assert.match(host, /serverEpoch === requestEpoch \|\| snapshot\.server_epoch === serverEpoch/)
  assert.match(host, /await live\.stop\(\)[\s\S]*if \(!isCurrentCommand\(commandToken\)\)[\s\S]*return/)
  assert.match(host, /\.finally\(\(\) => \{[\s\S]*if \(isCurrentCommand\(commandToken\)\)[\s\S]*return publishStatus\(\)/)
  assert.match(appContent, /toggleDesktopCodexLive\(projectPath\)/)
  assert.match(control, /sendDesktopCodexLiveCommand\('toggle', projectPath\)/)
  assert.match(bridge, /"start" \| "stop" \| "toggle" \| "mute" \| "short" \| "interrupt"/)
  assert.match(bridge, /requested_action == "toggle"/)
  assert.match(bridge, /requested_action == "short"[\s\S]{0,360}"stop"\.to_string\(\)/)
  assert.match(control, /sendDesktopCodexLiveCommand\('mute'\)/)
  assert.match(control, /setDesktopCodexLiveMicrophoneMuted/)
  assert.match(control, /microphone_muted: action === 'mute'/)
  assert.match(speechRuntime, /dispatch_desktop_codex_live_fn_action\("start"\)/)
  assert.match(speechRuntime, /dispatch_desktop_codex_live_fn_action\("short"\)/)
  assert.match(desktopLive, /type: 'response\.cancel'/)
  assert.match(desktopLive, /type: 'output_audio_buffer\.clear'/)
  assert.match(desktopLive, /sendControl\('interrupt'\)/)
  assert.match(desktopLive, /已取消当前对话，GPT-Live 继续聆听/)
  assert.match(speechRuntime, /issue_desktop_bridge_token/)
  assert.match(speechRuntime, /iterate-fn-live-dispatch/)
  assert.match(speechRuntime, /receive_fn_gesture_event/)
  assert.match(speechRuntime, /AmbiguousAfterDispatch/)
  assert.match(speechRuntime, /should_fallback_desktop_codex_live_fn_action/)
  assert.match(fnListener, /FN_LIVE_LONG_PRESS_US: u64 = 5_000_000/)
  assert.match(fnListener, /Released \{ observed_monotonic_us: u64 \}/)
  assert.doesNotMatch(appContent, /useDesktopCodexLive\(/)
  assert.doesNotMatch(appContent, /reportDesktopCodexLiveStatus/)
  assert.match(control, /\/api\/desktop-codex-live/)
  assert.match(control, /interface DesktopCodexLiveUiSnapshot/)
  assert.match(control, /execution_phase: DesktopCodexLiveExecutionPhase/)
  assert.match(control, /task_progress_text: string/)
  assert.match(control, /desktop-codex-live:\/\/ui-snapshot/)
  assert.match(control, /server_epoch/)
  assert.match(control, /host_id/)
  assert.match(bridge, /desktop_codex_live_capability_required/)
  assert.match(bridge, /request\.revision == live\.revision/)
  assert.match(bridge, /DESKTOP_CODEX_LIVE_HOST_LEASE_MS/)
  assert.match(bridge, /handle_desktop_codex_live_lease/)
  assert.match(publicControl, /"\/api\/desktop-codex-live\/lease"/)
  assert.match(appContent, /props\.showMcpPopup \? 1500 : 1000/)
  assert.match(appContent, /desktopCodexLiveToggleInFlight/)
  assert.match(appContent, /desktopCodexLiveMuteInFlight/)
  assert.match(appContent, /if \(desktopCodexLiveToggleInFlight\)[\s\S]{0,120}desktopCodexLiveToggleInFlight = true/)
  assert.match(appContent, /if \(desktopCodexLiveMuteInFlight\)[\s\S]{0,120}desktopCodexLiveMuteInFlight = true/)
  assert.match(mainLayout, /data-guide="global-codex-live"/)
  assert.match(mainLayout, /CODEX_LIVE_LONG_PRESS_MS = 5_000/)
  assert.match(mainLayout, /emit\('toggleCodexLiveMute'\)/)
  assert.match(tauriConfig, /main-capability[\s\S]{0,1400}core:window:allow-start-dragging/)
  assert.match(tauriConfig, /main-capability[\s\S]{0,1400}core:window:allow-available-monitors/)
  assert.match(tauriConfig, /main-capability[\s\S]{0,1400}core:window:allow-outer-position/)
  assert.match(tauriConfig, /main-capability[\s\S]{0,1400}core:window:allow-scale-factor/)
  assert.match(tauriConfig, /main-capability[\s\S]{0,1400}core:window:allow-set-size/)
  assert.match(tauriConfig, /main-capability[\s\S]{0,1400}core:window:allow-set-position/)
  assert.match(await read('src/rust/native_speech/overlay.rs'), /\.transparent\(true\)[\s\S]{0,80}\.shadow\(false\)/)
  assert.match(hudLayout, /await Promise\.all\(\[\s*mediaWindow\.setSize|await Promise\.all\(\[\s*hudWindow\.setSize/)
  assert.match(hudLayout, /storedCenterIsVisible[\s\S]{0,500}hudWindow\.scaleFactor\(\)[\s\S]{0,120}hudWindow\.outerPosition\(\)/)
  assert.doesNotMatch(tauriConfig, /desktop-codex-live-host-capability/)
  assert.match(host, /const confirmedLease = await renewDesktopCodexLiveLease/)
  assert.match(host, /if \(!confirmedLease\.granted\)/)
  assert.match(host, /const stopPromise = previousOwner && live\.isActive\.value[\s\S]*\? live\.stop\(\)[\s\S]*await hostWindow\.hide\(\)[\s\S]*await stopPromise/)
  assert.match(host, /catch \(error\)[\s\S]*if \(!isOwner\)[\s\S]*await demoteOwner\(\)/)
  assert.match(host, /const requestedEpoch = serverEpoch[\s\S]{0,300}serverEpoch !== requestedEpoch/)
})

test('desktop Live has a bounded microphone start and HUD mute control', async () => {
  const manager = await read('src/frontend/composables/useDesktopCodexLive.ts')

  assert.match(manager, /MICROPHONE_START_TIMEOUT_MS = 12_000/)
  assert.match(manager, /getUserMedia\.request/)
  assert.match(manager, /microphone_start_timeout/)
  assert.match(manager, /function toggleMicrophoneMuted\(\)/)
  assert.match(manager, /track\.enabled = !nextMuted/)
})

test('desktop Live accumulates realtime transcript deltas like iOS', async () => {
  const manager = await read('src/frontend/composables/useDesktopCodexLive.ts')
  const accumulator = await read('src/frontend/utils/codexLiveTranscript.ts')

  assert.match(manager, /advanceCodexLiveTranscript/)
  assert.match(manager, /let transcriptRole: string \| undefined/)
  assert.match(manager, /let transcriptFinalized = true/)
  assert.match(manager, /const rawText = message\.text \?\? ''/)
  assert.match(accumulator, /if \(isFinal\)/)
  assert.match(accumulator, /state\.role !== role \|\| state\.finalized/)
  assert.match(accumulator, /state\.text \+ rawText/)
  assert.match(accumulator, /role: role \?\? state\.role[\s\S]*finalized: true/)
})

test('desktop Live mirrors iOS execution display state without hiding ordinary transcript', async () => {
  const manager = await read('src/frontend/composables/useDesktopCodexLive.ts')
  const hudText = await read('src/frontend/utils/codexLiveHudText.ts')

  assert.match(manager, /const executionPhase = ref<DesktopCodexLiveExecutionPhase>\('waiting'\)/)
  assert.match(manager, /case 'task_started':[\s\S]*executionPhase\.value = 'running'/)
  assert.match(manager, /case 'task_progress':[\s\S]*message\.kind === 'agent'[\s\S]*slice\(-600\)[\s\S]*taskProgressText\.value = agentProgressBuffer[\s\S]*summarizeStatus\(agentProgressBuffer/)
  assert.match(manager, /case 'task_completed':[\s\S]*executionPhase\.value = 'completed'/)
  assert.match(manager, /executionPhase\.value === 'completed' \|\| executionPhase\.value === 'failed'/)
  assert.match(hudText, /executionActive[\s\S]*return taskProgressText \|\| statusText \|\| latestTranscript/)
  assert.match(hudText, /return latestTranscript \|\| statusText/)
})

test('Mac detects explicit tasks while keeping natural approval gated', async () => {
  const manager = await read('src/frontend/composables/useDesktopCodexLive.ts')
  const decisions = await read('src/frontend/utils/codexLiveVoiceDecision.ts')

  assert.match(manager, /isExplicitCodexLiveExecutionRequest/)
  assert.match(decisions, /awaitingConfirmation[\s\S]*isCodexLiveAffirmativeDecision/)
  assert.match(decisions, /EXECUTION_QUESTIONS\.includes\(normalized\)/)
  assert.doesNotMatch(decisions, /EXECUTION_QUESTIONS\.some[\s\S]*includes/)
  assert.match(decisions, /explicitRequestPending[\s\S]*isDirectCodexLiveExecutionCommand/)
  assert.match(decisions, /CAPABILITY_QUESTION_MARKERS/)
  assert.match(manager, /explicitExecutionRequestPending/)
  assert.match(manager, /isExplicitCodexLiveExecutionRequest/)
  assert.match(manager, /scheduleReconnect[\s\S]*explicitExecutionRequestPending = false/)
})

const iosManagerUrl = new URL('ios-app/IterateNotify/CodexLiveManager.swift', root)

test('iOS keeps natural approval gated when the private client source is available', {
  skip: !existsSync(iosManagerUrl),
}, async () => {
  const iosManager = await read('ios-app/IterateNotify/CodexLiveManager.swift')

  assert.match(iosManager, /CharacterSet\.whitespacesAndNewlines[\s\S]*\.union\(\.punctuationCharacters\)[\s\S]*\.union\(\.symbols\)/)
  assert.match(iosManager, /return normalized == "需求已经确认是否现在开始执行"/)
  assert.doesNotMatch(iosManager, /isExecutionConfirmationQuestion[\s\S]{0,800}contains\(where: normalized\.contains\)/)
  assert.match(iosManager, /private static func isDirectVoiceExecutionCommand/)
  assert.match(iosManager, /private static func isExplicitExecutionRequest/)
  assert.match(iosManager, /connectBroker[\s\S]*finalizedUserUtteranceCount = 0[\s\S]*awaitingVoiceExecutionConfirmation = false/)
  assert.match(iosManager, /else if awaitingVoiceExecutionConfirmation,[\s\S]*Self\.isAffirmativeVoiceDecision\(text\)[\s\S]*confirmExecution\(\)/)
  assert.match(iosManager, /else if explicitExecutionRequestPending,[\s\S]*Self\.isDirectVoiceExecutionCommand\(text\)[\s\S]*confirmExecution\(\)/)
  assert.doesNotMatch(iosManager, /else if Self\.isAffirmativeVoiceDecision\(text\) \{\s*awaitingVoiceExecutionConfirmation = false\s*if priorUserUtteranceCount/)
})

test('Mac and iOS resume one project-scoped Codex thread through bounded continuity', async () => {
  const liveBridge = await read('src/rust/bridge/codex_live.rs')
  const continuity = await read('src/rust/bridge/codex_live/continuity.rs')

  assert.match(liveBridge, /spawn_blocking[\s\S]*continuity::load\(&continuity_project_path\)/)
  assert.match(liveBridge, /"thread\/resume"/)
  assert.match(liveBridge, /resume_thread_params\(thread_id, project_path\)/)
  assert.match(liveBridge, /"config": realtime_thread_config\(\)/)
  assert.match(liveBridge, /"mcp_servers\.iterate-zhi\.enabled": false/)
  assert.match(liveBridge, /"agents\.enabled": true/)
  assert.match(liveBridge, /"agents\.max_concurrent_threads_per_session": 3/)
  assert.match(liveBridge, /resume_thread_params[\s\S]*"developerInstructions": CODEX_VOICE_DEVELOPER_INSTRUCTIONS/)
  assert.match(liveBridge, /continuity::store_thread/)
  assert.match(liveBridge, /continuity::append_transcript/)
  assert.match(liveBridge, /"includeStartupContext": false/)
  assert.match(liveBridge, /params\["initialItems"\] = Value::Array\(initial_items\)/)
  assert.doesNotMatch(liveBridge, /"realtimeSessionId"\s*:/)
  assert.match(continuity, /MAX_ITEMS: usize = 10/)
  assert.match(continuity, /MAX_ITEM_CHARS: usize = 1_200/)
  assert.match(continuity, /MAX_TOTAL_CHARS: usize = 8_000/)
  assert.match(continuity, /codex-live-continuity-v1\.json/)
  assert.match(continuity, /Permissions::from_mode\(0o600\)/)
  assert.match(continuity, /LOCK_EX \| libc::LOCK_NB/)
  assert.match(continuity, /\.quarantine-/)
  assert.match(continuity, /bounded historical transcript/)
  assert.match(liveBridge, /if completion\.requires_interrupt \{[\s\S]*interrupt_active_execution_or_confirm_idle[\s\S]*self\.execution_turn_id = None/)
  assert.match(liveBridge, /Some\("thread\/realtime\/error"\)[\s\S]*requires_interrupt: true/)
  assert.match(liveBridge, /Some\("turn\/started"\)[\s\S]*self\.execution_active && self\.execution_turn_id\.is_none\(\)[\s\S]*self\.execution_turn_id = Some/)
  assert.match(liveBridge, /Err\(error\) => \{[\s\S]*interrupt_active_execution_or_confirm_idle\(\)\.await[\s\S]*cleanup\.is_ok\(\)[\s\S]*self\.execution_active = false/)
  assert.match(liveBridge, /if cancelled \{[\s\S]*start_future\.as_mut\(\)\.await/)
  assert.match(liveBridge, /"thread\/realtime\/start"[\s\S]*process\.stop\(\)\.await/)
})
